### PR TITLE
Add ING application practice cases for zh

### PR DESCRIPTION
**Pull request by wangyang0616**
Signed-off-by: wangyang <wangyang8126@gmail.com>

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

/kind documentation

* **What this PR does / why we need it**:

Added Volcano case sharing: The big data platform application practice using Volcano shared by ING Bank at Kubecon North America in 2022

* **Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
close reopen to retrigger the CI checks

**Comment by kevin-wangzefeng** [comment]
The following failed checks are irrelevant, not from volcano netlify build config.

Check | Status
----- | -------
Header rules - kind-montalcini-bed86a  |  Deploy failed | [Details](https://app.netlify.com/sites/kind-montalcini-bed86a/deploys/63abfd49a6c4f10009773f8c)
Mixed content - kind-montalcini-bed86a  |  Deploy failed [Details](https://app.netlify.com/sites/kind-montalcini-bed86a/deploys/63abfd49a6c4f10009773f8c)
Pages changed - kind-montalcini-bed86a  |  Deploy failed  [Details](https://app.netlify.com/sites/kind-montalcini-bed86a/deploys/63abfd49a6c4f10009773f8c)
Redirect rules - kind-montalcini-bed86a  |  Deploy failed  [Details](https://app.netlify.com/sites/kind-montalcini-bed86a/deploys/63abfd49a6c4f10009773f8c)
netlify/kind-montalcini-bed86a/deploy-preview  |  Deploy Preview failed. Required [Details](https://app.netlify.com/sites/kind-montalcini-bed86a/deploys/63abfd49a6c4f10009773f8c)

**Comment by kevin-wangzefeng** [comment]
It seems the new blog not shown in the home page blog list.
/lgtm cancel
/approve cancel

**Comment by kevin-wangzefeng** [comment]
> It seems the new blog not shown in the home page blog list. /lgtm cancel /approve cancel

nevermind, I forgot to switch language.

**Comment by kevin-wangzefeng** [comment]
Sorry for the buzzing.
/lgtm
/approve

**Comment by william-wang** [comment]
please make the ci happy.

**Comment by wangyang0616** [comment]
> please make the ci happy.

After the adjustment, the CI has passed, please help to review

**Review by Thor-wl — APPROVED** [review]
/lgtm

**Pull request merged**
