### PR TITLE
refactor js

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/278

### CODE REVIEW

**Review by Thor-wl — COMMENTED** [review]
Hi, @Arhell . Perhaps these modifications depend on the developer's coding habit. So are there someting else making more sense we can help?

**Comment by Arhell** [comment]
> Hi, @Arhell . Perhaps these modifications depend on the developer's coding habit. So are there someting else making more sense we can help?

Maybe I would say that this is a minor fix.

**Comment by Arhell** [comment]
@Thor-wl  can be merged into master branch minor fix

**Review by Thor-wl — APPROVED** [review]

**Pull request merged**
