### PR TITLE
update search block on mobile

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/141
/kind design

### CODE REVIEW

**Comment by Thor-wl** [comment]
Hey, just a friendly reminder, please rebase all the commits into one and submit the PR again. Thanks!
@Arhell

**Comment by Arhell** [comment]
> Hey, just a friendly reminder, please rebase all the commits into one and submit the PR again. Thanks!

Of course, as the result suits me, I will do

**Comment by Arhell** [comment]
Done @Thor-wl
I moved the block with search and social networks to the navigation block, corrected everything.

**Pull request merged**
