### PR TITLE
Accessibility update search bar

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/308

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@kevin-wangzefeng  fix issue https://github.com/volcano-sh/website/issues/308

**Comment by Arhell** [comment]
cc @kevin-wangzefeng

**Comment by hwdef** [comment]
Please add what it looks like before and after the modification

**Comment by Arhell** [comment]
> Please add what it looks like before and after the modification

Visually nothing has changed
But the check (Accessibility Insights for Web) does not give an error, the example is taken from the bootstrap site, this role is not there

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve
Thanks

**Pull request merged**
