### PR TITLE
Fix website installation

### PR DESCRIPTION
**Pull request by ccchenjiahuan**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What this PR does / why we need it**:

* **Which issue(s) this PR fixes**:

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by hwdef — COMMENTED** [review]
Please change this in zh docs too.

**Comment by shinytang6** [comment]
> Please change this in zh docs too.

Thanks, l changed it

**Review by shinytang6 — APPROVED** [review]
Thanks for changing it, LGTM overall

**Review by Thor-wl — APPROVED** [review]

**Pull request merged**
