### PR TITLE
update favicons

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/248

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @Thor-wl
added and updated icons

**Comment by Thor-wl** [comment]
Kindly to ask what's the difference between the deleted pictures and the added ones? I'm sorry for not picking out the difference by the naked eye.

**Comment by Arhell** [comment]
> Kindly to ask what's the difference between the deleted pictures and the added ones? I'm sorry for not picking out the difference by the naked eye.

small, they are generated from svg and not png file, better quality

**Comment by Thor-wl** [comment]
> > Kindly to ask what's the difference between the deleted pictures and the added ones? I'm sorry for not picking out the difference by the naked eye.
> 
> small, they are generated from svg and not png file, better quality

Got it. 
/lgtm
/approve

**Pull request merged**
