### PR TITLE
update supporter links

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/228

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @Thor-wl
links checked

**Comment by Thor-wl** [comment]
@Arhell Hi, I've double checked this link. It seems to use `http` indeed. Please take a review.
/hold

**Comment by Arhell** [comment]
@Thor-wl
I checked again, 1-well, the link was revert
qutoutiao works

**Pull request merged**
