### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Hiiirad**
Added .DS_Store

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What this PR does / why we need it**:

* **Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by Thor-wl** [comment]
Hey, why remove the .vcscode file? Perhaps that files which are related with IDE will not been included may be better.

**Comment by Hiiirad** [comment]
> Hey, why remove the .vcscode file? Perhaps that files which are related with IDE will not been included may be better.

I didn't remove .vscode file. When I added a new line to add .DS_Store, it happened like this.

**Comment by Thor-wl** [comment]
> > Hey, why remove the .vcscode file? Perhaps that files which are related with IDE will not been included may be better.
> 
> I didn't remove .vscode file. When I added a new line to add .DS_Store, it happened like this.

I'm sorry for my mistake. Yes, it's OK to me.

**Comment by Thor-wl** [comment]
> > > Hey, why remove the .vcscode file? Perhaps that files which are related with IDE will not been included may be better.
> > 
> > 
> > I didn't remove .vscode file. When I added a new line to add .DS_Store, it happened like this.
> 
> I'm sorry for my mistake. Yes, it's OK to me. Pls fix the DCO and then I'll merge this PR. Thanks!

**Review by Arhell — COMMENTED** [review]
Plsease Signed-off-by: Author Name
link https://github.com/volcano-sh/website/pull/173/checks?check_run_id=5629321332

**Comment by kevin-wangzefeng** [comment]
close in favor of https://github.com/volcano-sh/website/pull/218/ merged.
/close

**Pull request closed without merging**
