### PR TITLE
doc: fix schedulerName typo description

### PR DESCRIPTION
**Pull request by calebeof**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Documentation update.

* **What this PR does / why we need it**:

Fixes the broken schedulerName selection.

* **Which issue(s) this PR fixes**:
No issue was created before.

### CODE REVIEW

**Review by calebeof — COMMENTED** [review]
/assign @william-wang

**Comment by Monokaix** [comment]
/lgtm
Thanks for your contribution！

**Comment by william-wang** [comment]
@calebeof Thanks for your contribution :)

**Pull request merged**
