### PR TITLE
repaired How to contributing link

### LINKED ISSUE #254: Link to contribution.md page is broken
In this [readme](https://github.com/volcano-sh/website/blob/master/README.md) , inside the header `Creating and updating the docs`. 

`How to contributing` link is broken.

### PR DESCRIPTION
**Pull request by Rahulkumar2002**
* **Repaired `How to contributing` in README.md**
- [ ] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (documentation)

* **It repaired the link `How to contributing` in [README.md](https://github.com/volcano-sh/website/blob/master/README.md) and redirect it to the [contribute.md](https://github.com/volcano-sh/volcano/blob/master/contribute.md)**:

* **Fixes #254 **:

### CODE REVIEW

**Comment by Rahulkumar2002** [comment]
@Thor-wl can you please review this PR. 
Also I can't be able to join the slack channel.
Can you do something about it?

**Comment by Thor-wl** [comment]
@Rahulkumar2002 Hey, welcome to volcano community! Thanks for your contribution! Please leave your email here and I'll send an invitation for you.

**Review by Thor-wl — APPROVED** [review]

**Comment by Rahulkumar2002** [comment]
Thank you @Thor-wl for this warm welcome .
Email : rahuljhakumar1600@gmail.com

**Pull request merged**
