### PR TITLE
add Volcano v1.7.0 release blog for zh

### PR DESCRIPTION
**Pull request by wangyang0616**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

/kind documentation

* **What this PR does / why we need it**:
Volcano 1.7.0 has been officially released, the article mainly introduces the new features and functions of this version

* **Which issue(s) this PR fixes**:

### CODE REVIEW

**Review by Thor-wl — APPROVED** [review]

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
