### PR TITLE
add svg slack icon

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/volcano-sh/website/issues/230

### CODE REVIEW

**Comment by Thor-wl** [comment]
I'm not an expert of front end and design. May I ask that why replace the `png` with `svg`? I see there seems to be smaller pixel.

**Comment by Arhell** [comment]
> I'm not an expert of front end and design. May I ask that why replace the `png` with `svg`? I see there seems to be smaller pixel.

that's right, the icon is better and the pixels will not be visible

**Comment by kevin-wangzefeng** [comment]
Thanks @Arhell , I'd like to confirm if the logo comes from cncf/artwork (which is considered as the canonical source).

**Comment by kevin-wangzefeng** [comment]
https://github.com/cncf/artwork

**Comment by Arhell** [comment]
> 

no
https://commons.wikimedia.org/wiki/File:Slack_icon_2019.svg

**Comment by Arhell** [comment]
> I'd like to confirm if the logo comes from cncf/artwork (which is considered as the canonical source).

no, there is no slack, I updated it and took it from https://brandfolder.com/slack/logos

**Comment by kevin-wangzefeng** [comment]
Sorry, I misunderstood the PR. It looks fine to me then, could you reopen it?

**Comment by kevin-wangzefeng** [comment]
Sure

**Pull request closed without merging**
